# Aeccess Token - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmI5ODg3YWYzMGY2MDI3MzBlY2I1YiIsImlhdCI6MTcxMjA1MTcyNH0.Zaw2sbHPlxCQLlUi25acHGj1K16Kj7rjD1YU-kywF4E

POST http://localhost:3000/login
Content-Type: application/json

{
   "email" : "john1@gmail.com",
   "password" : "John123"
}


# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname" : "john",
#     "email" : "john1@gmail.com",
#     "password" : "John123"
# }


# POST http://localhost:3000/change-password
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmI5ODg3YWYzMGY2MDI3MzBlY2I1YiIsImlhdCI6MTcxMjA1MTcyNH0.Zaw2sbHPlxCQLlUi25acHGj1K16Kj7rjD1YU-kywF4E

# {
#    "currentPassword": "Aryan123",
#    "newPassword": "John123"
# }
